[tool.poetry]
name = "KhristinaR_brain_games"
version = "0.1.0"
description = ""
authors = ["Khristina Rustanovich <khristina.analytics@gmail.com>"]
packages = [
    { include = "brain_games" },
  ]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"
